# Generated by Django 6.0.4 on 2026-04-12 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("model_name", models.CharField(max_length=100)),
                ("object_id", models.CharField(max_length=100)),
                ("before_data", models.JSONField(blank=True, null=True)),
                ("after_data", models.JSONField(blank=True, null=True)),
                ("reason", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DayLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lock_date", models.DateField()),
                ("locked_at", models.DateTimeField(auto_now_add=True)),
                ("is_locked", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-lock_date", "section__name"],
            },
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="section",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="worker",
            options={"ordering": ["name"]},
        ),
        migrations.RenameIndex(
            model_name="productionentry",
            new_name="production__entry_d_395b46_idx",
            old_name="production_entry_idx",
        ),
        migrations.AddField(
            model_name="auditevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="daylock",
            name="locked_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="day_locks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="daylock",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="production.section"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="daylock",
            unique_together={("section", "lock_date")},
        ),
    ]
