# Generated by Django 4.2.7 on 2026-04-18 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0002_auditevent_dailyledger_daylock_processflowedge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_date', models.DateField()),
                ('waste_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste_entries', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.item')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.section')),
            ],
            options={
                'ordering': ['-waste_date', 'section__name', 'item__name'],
                'indexes': [models.Index(fields=['waste_date', 'section', 'item'], name='production__waste_d_dc4546_idx')],
            },
        ),
    ]
