# Generated by Django 4.2.7 on 2026-04-21 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0003_wasteentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sheets', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.section')),
            ],
            options={
                'ordering': ['-attendance_date', 'section__name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], default='PRESENT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='production.attendancesheet')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.worker')),
            ],
            options={
                'ordering': ['worker__name'],
            },
        ),
        migrations.AddIndex(
            model_name='attendancesheet',
            index=models.Index(fields=['attendance_date', 'section'], name='production__attenda_591590_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesheet',
            unique_together={('attendance_date', 'section')},
        ),
        migrations.AddIndex(
            model_name='attendanceline',
            index=models.Index(fields=['sheet', 'status'], name='production__sheet_i_679113_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendanceline',
            unique_together={('sheet', 'worker')},
        ),
    ]
