# Generated by Django 6.0.4 on 2026-04-19 19:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0003_wasteentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attendance_date", models.DateField(default=datetime.date.today)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_sheets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="production.section",
                    ),
                ),
            ],
            options={
                "ordering": ["-attendance_date", "section__name"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_present", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="production.worker",
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="production.attendancesheet",
                    ),
                ),
            ],
            options={
                "ordering": ["worker__name"],
            },
        ),
        migrations.AddIndex(
            model_name="attendancesheet",
            index=models.Index(
                fields=["attendance_date", "section"],
                name="production__attenda_591590_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendancesheet",
            unique_together={("attendance_date", "section")},
        ),
        migrations.AlterUniqueTogether(
            name="attendanceline",
            unique_together={("sheet", "worker")},
        ),
    ]
