# Generated by Django 4.2.7 on 2026-04-22 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0004_attendancesheet_attendanceline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('machine_code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='production.section')),
            ],
            options={
                'ordering': ['section__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MachineDowntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downtime_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machine_downtimes', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='downtimes', to='production.machine')),
            ],
            options={
                'ordering': ['-downtime_date', 'machine__name', '-start_time'],
                'indexes': [models.Index(fields=['downtime_date', 'machine'], name='production__downtim_281a58_idx')],
            },
        ),
    ]
