# Generated by Django 4.2.7 on 2026-04-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_requisition_statushistory_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dailyledger',
            index=models.Index(fields=['date', 'section', 'item'], name='production__date_103845_idx'),
        ),
        migrations.AddIndex(
            model_name='productionentry',
            index=models.Index(fields=['entry_date', 'section'], name='production__entry_d_1b4455_idx'),
        ),
        migrations.AddIndex(
            model_name='productionentry',
            index=models.Index(fields=['worker', 'entry_date'], name='production__worker__a34f26_idx'),
        ),
    ]
