# Generated by Django 5.2.13 on 2026-05-03 03:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_dailyledger_production__date_103845_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionentry',
            name='difficulty_factor_snapshot',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='targetrule',
            name='difficulty_factor',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5),
        ),
    ]
